#ifndef FINITETHICKNESSVERTEXMESHFROMREADERGENERATOR_HPP_
#define FINITETHICKNESSVERTEXMESHFROMREADERGENERATOR_HPP_

#include <cmath>
#include <vector>

#include "MonolayerVertexMeshReader.hpp"
#include "MutableMonolayerVertexMesh.hpp"

/**
 * Generate a MutableMonolayerVertexMesh from files generated by MonolayerVertexMeshWriter. A MonolayerVertexMeshReader with the corresponding file path to the directory is required. In the directory, three files have to exist: *.node, *.face, *.cell.
 *
 * NOTE: the user should delete the mesh after use to manage memory.
 */

class FiniteThicknessVertexMeshFromReaderGenerator
{
private:
    /** A pointer to the mesh this class creates */
    MutableMonolayerVertexMesh<3, 3>* mpMesh;

public:
    /**
     * Constructor.
     *
     * @param cellRearrangementThreshold the minimum threshold distance for
     * element rearrangement (defaults to 0.01)
     * @param t2Threshold the maximum threshold distance for Type 2 swaps
     * (defaults to 0.001)
     *
     */
    FiniteThicknessVertexMeshFromReaderGenerator(
        MonolayerVertexMeshReader<3, 3>& mesh_reader,
        double cellRearrangementThreshold = 0.01,
        double t2Threshold = 0.001);

    /**
     * Destructor - deletes the mesh object and pointer.
     */
    virtual ~FiniteThicknessVertexMeshFromReaderGenerator();

    /**
     * @return a 3D spherical mesh
     */
    virtual MutableMonolayerVertexMesh<3, 3>* GetMesh();

    c_vector<double, 3> GetNormalToFace(MonolayerVertexElement<2, 3>* pFace);

    c_vector<double, 3> GetCenterOfFace(MonolayerVertexElement<2, 3>* pFace);
};

#endif /*FINITETHICKNESSVERTEXMESHFROMREADERGENERATOR_HPP_*/